# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IntervalsMcp < Formula
  desc "Dynamic MCP server for the Intervals.icu API"
  homepage "https://github.com/derrix060/intervals-mcp"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/derrix060/intervals-mcp/releases/download/v1.0.0/intervals-mcp_Darwin_x86_64.tar.gz"
      sha256 "475fe36eab2c9e4aedd583649c73213e9543ce915d177f137e5df4753b78cc58"

      define_method(:install) do
        bin.install "intervals-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/derrix060/intervals-mcp/releases/download/v1.0.0/intervals-mcp_Darwin_arm64.tar.gz"
      sha256 "a9d259e7a1f02c560c3b6360c196e9cc5221e58e555af8a28f3fdb22e80dec43"

      define_method(:install) do
        bin.install "intervals-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/derrix060/intervals-mcp/releases/download/v1.0.0/intervals-mcp_Linux_x86_64.tar.gz"
      sha256 "bd73ce87cb6942735e386a171fdf558ad179a25d9f8b3608dd8d9fe3355b92d1"
      define_method(:install) do
        bin.install "intervals-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/derrix060/intervals-mcp/releases/download/v1.0.0/intervals-mcp_Linux_arm64.tar.gz"
      sha256 "ba21fe88e0afd4ada086cec1c2d1d0f3ea0a96fe096f171115b5b499702c8a30"
      define_method(:install) do
        bin.install "intervals-mcp"
      end
    end
  end

  test do
    assert_match "INTERVALS_API_KEY", shell_output("#{bin}/intervals-mcp 2>&1", 1)
  end
end
